language: java
jdk:
  - openjdk6
before_install:
  - sudo add-apt-repository -y ppa:groovy-dev/grails
  - sudo apt-get update
  - sudo apt-get install grails-1.3.7
  - gem install sass --version 3.1.3 &> /dev/null
  - gem install compass –version 0.11.3 &> /dev/null
install: /bin/true
script: ant bundle
branches:
  only:
    - master