language: groovy
jdk:
  - openjdk6
rvm:
  - 1.9.2
before_install:
  - groovy --version
  - gem install sass --version 3.1.3 &> /dev/null
  - gem install compass --version 0.11.3 &> /dev/null
  - sudo add-apt-repository -y ppa:groovy-dev/grails
  - sudo apt-get update
  - sudo apt-get install grails-1.3.7
  - ant init-build
install: /bin/true
script:  ant bundle -Dgroovy_all=/usr/share/java/groovy-all.jar
branches:
  only:
    - master